### ISSUE TITLE
Parameters of runUPTBQueries

### ISSUE THREAD

**Issue by root676** [kit-algo/ULTRA#26]
First of all, I want to thank you for sharing all the information and code on your thesis - this is not only an outstanding contribution in the field of informatics, it pushes research in mobility science too. 

Being impressed by the performance of `ULTRA` (esp. ULTRATB), I tested `UPTB` with a national dataset too. While exploring the commands in the `ULTRAPHAST` application together with the thesis provided, I ran into some confusion regarding the parameters. I have computed all necessary datasets/shortcuts to run ULTRATB successfully, but I struggle to get UPTB to run with those inputs. 

Could you provide me some guidance on how to use UPTB with the data from the 1:1 ULTRA algorithms? I assumed following data inputs for the UPTB parameters:

- `<Trip-Based data>`: Trip based data from `computeEventToEventShortcuts`
- `<Dijkstra graph>`: ?.graph files from the original raptor.binary computation (before `computeEventToEventShortcuts`)?
- `<CH Data>`: ?buildCH output for raptor.binary.graph?
- `<Number of queries>`: Query count (int)
- `<reorder network>`: ?
- `<Order>`: ?
- `<grouped rounds>`: ?
- `<targets>`: Vertices

Especially the functions `buildCoreCHForTargetSets` and `buildUPCHForTargetSets` add to my confusion. Is it necessary to compute CHs for UPTB that differ from the ones computed from the original raptor.binary for ULTRATB? 

Thank you in advance for the info!

**Comment by jonas-sauer** [comment]
Since you set `<Targets>` to Vertices, I assume you want to perform a one-to-all search to all vertices in the transfer graph. My guess is that you used a contracted transfer graph in a place where the algorithm expected the full, uncontracted graph. Here's an example of how you would set it up using the data in https://i11www.iti.kit.edu/PublicTransitData/ULTRA/Switzerland/Walking/

* `<Trip-Based data>`: The output of `computeEventToEventShortcuts` for `Contracted/raptor.binary`
* `<Dijkstra graph>`: `Full/raptor.binary.graph`
* `<CH data>`: The output of `buildCH` for `Full/raptor.binary.graph`
* `<Number of queries>`: Query count
* `<Reorder network?>`: true (This is faster; the other option exists only for benchmarking and debugging)
* `<Order>`: DFS (This is faster; the other option exists only for benchmarking)
* `<Grouped rounds>`: 6 (This usually performs best)
* `<Targets>`: Vertices

The command `buildUPCHForTargetSets` is not needed in your case. If you have a target set that does not include all vertices, then you can improve the performance of UP-TB by delaying the contraction of the targets during the CH computation. This is described in my thesis under "Optimized Contraction Order" in Chapter 6.1.1. In this case, you would use `buildUPCHForTargetSets` instead of `buildCH`for `<CH data>`.

**Comment by root676** [comment]
Thank you very much for the detailed explanation! This solved the issue.
